<?php

namespace adminBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyfindAll(){
        // Création d'une requête grâce au builder
        // findAll() maison
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select("prod")
            ->from("adminBundle:Product", "prod")
            ->getQuery();

         return $query->getResult();
    }

    public function myFind($id)
    {

        // Creation d'une requête DQL
        // find() maison
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('prod')
            ->from("adminBundle:Product","prod")
            ->where('prod.id = :identifiant')
            ->setParameter('identifiant', $id)
            ->getQuery();

        return $query->getOneOrNullResult();
    }


    public function quantitySmallAll()
    {
        $q = 5;

        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('prod')
            ->from("adminBundle:Product","prod")
            ->where('prod.quantity < :quantity')
            ->setParameter('quantity', $q)
            ->getQuery();

        return $query->getResult();
    }

    public function quantityZeroAll()
    {
        $q = 0;

        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('prod')
            ->from("adminBundle:Product","prod")
            ->where('prod.quantity = :quantity')
            ->setParameter('quantity', $q)
            ->getQuery();

        return $query->getResult();
    }





}
